### ISSUE TITLE
MiAulario no tiene icono

### ISSUE THREAD

**Issue by igargi** [CEUPNA/backend-ceupna#20]
{"id":3,"created":"2017-09-17T22:32:16.348598Z","name":"MiAulario",**"icon":""**,"description":"Esta es la plataforma donde estÃ¡n todos los recursos necesarios para las asignaturas.","web":"https://miaulario.unavarra.es","last_updated":"2017-09-17T22:32:16.348666Z"}

**Comment by igargi** [comment]
También editar el icono de eduroam para que sea cuadrado, en vez de rectangular.

**Comment by iaguas** [comment]
Problema de MiAulario solucionado... aunque un poco de aquella manera con un favicon... pero sirve.

**Comment by iaguas** [comment]
Tema de Eduroam también solucionado. Cierro este bug.
