### ISSUE TITLE
Los test no funcionan de manera correcta

### ISSUE THREAD

**Issue by iaguas** [CEUPNA/backend-ceupna#29]
Aun cuando no se utilizan ni se han escrito los tests, cuando estos se han intentado poner en marcha se ha encontrado el siguiente error:

![captura de pantalla 2018-01-24 a las 2 13 38](https://user-images.githubusercontent.com/4259550/35309708-149dbfdc-00ae-11e8-9212-7c74df032960.png)

**Comment by iaguas** [comment]
Se ha incluido una pregunta en [stackoverflow](https://stackoverflow.com/questions/48413412/django-import-error-in-test) sobre el tema. Veremos qué pasa...

**Comment by martinarroyo** [comment]
@iaguas Es seguramente un problema en la resolución de módulos. Debería ser fácil de solucionar. Si quieres le echo un ojo.

**Comment by iaguas** [comment]
Se ha reorganizado el proyecto, haciéndolo más coherente con la organización de Django. Esto ha permitido que el error desaparezca "solo".
